In [1]:
import numpy as np
import pandas as pd


In [2]:
df=pd.read_csv("C:/Users/debas/Downloads/placement_dataset.csv")

In [3]:
df.head()

CGPA     IQ  12th Marks (%)  Placement Package (LPA)
0  8.10   99.0           93.87                    40.69
1  7.33  114.0           87.04                    36.68
2  8.28  115.0           84.85                    41.01
3  9.33  108.0           85.12                    42.77
4  7.22  118.0           67.97                    32.23

In [4]:
x=df.iloc[:,0:3]
y=df.iloc[:,3]

In [5]:
x.head()

CGPA     IQ  12th Marks (%)
0  8.10   99.0           93.87
1  7.33  114.0           87.04
2  8.28  115.0           84.85
3  9.33  108.0           85.12
4  7.22  118.0           67.97

In [6]:
y.head()

0    40.69
1    36.68
2    41.01
3    42.77
4    32.23
Name: Placement Package (LPA), dtype: float64

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [8]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [9]:
from sklearn.metrics import r2_score
y_pred=reg.predict(x_test)

In [10]:
y_pred

array([30.29151014, 27.80904705, 36.4728954 , 32.83905889, 36.41046191,
       29.62595343, 39.23740107, 31.45591516, 37.22922282, 35.06294843,
       33.75905801, 29.128131  , 35.92382055, 32.12197112, 38.9605305 ,
       28.97165643, 41.29623177, 32.62923311, 38.78625915, 32.96343427])

In [11]:
y_test

83    31.37
30    27.28
56    37.68
24    33.89
16    34.97
23    28.51
2     41.01
27    31.10
28    36.76
13    33.29
99    34.14
92    27.26
76    34.26
14    33.55
0     40.69
21    30.25
3     42.77
29    33.78
61    38.98
79    32.60
Name: Placement Package (LPA), dtype: float64

In [12]:
r2_score(y_test,y_pred)

0.917003018679725

In [94]:
 class GDRegressor:
    
    def __init__(self,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            # update all the coef and the intercept
            y_hat = np.dot(X_train,self.coef_) + self.intercept_
            #print("Shape of y_hat",y_hat.shape)
            intercept_der = -2 * np.mean(y_train - y_hat)
            self.intercept_ = self.intercept_ - (self.lr * intercept_der)
            
            coef_der = -2 * np.dot((y_train - y_hat),X_train)/X_train.shape[0]
            self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_


    

In [142]:
gdr=GDRegressor(epochs=10,learning_rate=0.1)

In [143]:
gdr.fit(x_train,y_train)

9.861006139935746e+33 [7.39052380e+34 1.19752648e+36 7.42483025e+35]


In [144]:
y_pred = gdr.predict(x_test)

In [145]:
y_pred

array([1.91413780e+38, 1.58509926e+38, 2.35236160e+38, 2.02760961e+38,
       2.13144283e+38, 1.76260610e+38, 2.01337026e+38, 1.73232968e+38,
       2.13074121e+38, 2.49660675e+38, 1.81267773e+38, 1.85909481e+38,
       1.99649103e+38, 2.03707070e+38, 1.88860497e+38, 1.65942624e+38,
       1.93232412e+38, 1.85157520e+38, 2.23135737e+38, 2.45220362e+38])

In [146]:
r2_score(y_test,y_pred)

-2.1810477045900194e+75

In [147]:
y_test

83    31.37
30    27.28
56    37.68
24    33.89
16    34.97
23    28.51
2     41.01
27    31.10
28    36.76
13    33.29
99    34.14
92    27.26
76    34.26
14    33.55
0     40.69
21    30.25
3     42.77
29    33.78
61    38.98
79    32.60
Name: Placement Package (LPA), dtype: float64

In [148]:
y_pred

array([1.91413780e+38, 1.58509926e+38, 2.35236160e+38, 2.02760961e+38,
       2.13144283e+38, 1.76260610e+38, 2.01337026e+38, 1.73232968e+38,
       2.13074121e+38, 2.49660675e+38, 1.81267773e+38, 1.85909481e+38,
       1.99649103e+38, 2.03707070e+38, 1.88860497e+38, 1.65942624e+38,
       1.93232412e+38, 1.85157520e+38, 2.23135737e+38, 2.45220362e+38])